/**
 * HeroUI v3 framework adapter.
 *
 *   tokens     ← derive.ts (raw OKLCH data → static per-theme hex)
 *   components ← catalog.ts (~72 atomic components)
 *   mockups    ← a seed `template` screen built from LOCAL component refs
 *
 * Mockups instantiate components via `ctx.component(id)` → a bare,
 * local id (the emitter is single-file; cross-file refs can't be
 * customized via `descendants`). Customization uses `descendants`
 * keyed by the component's direct child ids (verified to work for
 * local refs) and root-level overrides set straight on the ref.
 */

import type { ComponentSpec } from '../../design-system/atomic.ts';
import type { TokenSet } from '../../design-system/tokens.ts';
import { frame, ref, text } from '../../pen/builder.ts';
import type { Child } from '../../pen/schema.ts';
import type { FrameworkAdapter, MockupContext, MockupSpec } from '../_core/adapter.ts';
import { catalogStats, heroUIComponents } from './catalog.ts';
import { type DeriveResult, deriveHeroUITokens } from './derive.ts';

let cached: DeriveResult | undefined;
function derived(): DeriveResult {
  if (!cached) cached = deriveHeroUITokens();
  return cached;
}

/**
 * The seed mockup template (a marketing-homepage starter assembled
 * from local component refs). Emitted as `mocks/template.pen`; the
 * CLI copies+renames it when creating a new mockup.
 */
function templateMockup(): MockupSpec {
  return {
    slug: 'template',
    name: 'Template',
    build: (ctx: MockupContext): Child[] => {
      // Inline header — HeroUI v3 has no Navbar component, so this is
      // a plain frame rather than a component ref.
      const navbar = frame(
        'hp-nav',
        {
          name: 'Nav',
          layout: 'horizontal',
          width: 'fill_container',
          justifyContent: 'space_between',
          alignItems: 'center',
        },
        [
          text('hp-brand', 'mech-pencil', {
            fill: ctx.token('color.foreground'),
            fontFamily: ctx.token('font.family'),
            fontSize: 18,
            fontWeight: '700',
          }),
          text('hp-navlinks', 'Docs   Components   Pricing', {
            fill: ctx.token('color.muted'),
            fontFamily: ctx.token('font.family'),
            fontSize: 14,
          }),
        ],
      );

      const hero = frame(
        'hp-hero',
        { name: 'Hero', layout: 'vertical', width: 'fill_container', gap: 20 },
        [
          text('hp-eyebrow', 'HeroUI v3 · generated by mech-pencil', {
            fill: ctx.token('color.muted'),
            fontFamily: ctx.token('font.family'),
            fontSize: 14,
            fontWeight: '600',
          }),
          text('hp-title', 'Build interfaces that feel inevitable.', {
            fill: ctx.token('color.foreground'),
            fontFamily: ctx.token('font.family'),
            fontSize: 56,
            fontWeight: '800',
          }),
          text(
            'hp-sub',
            'A themeable design system, assembled from reusable components and design tokens.',
            {
              fill: ctx.token('color.muted'),
              fontFamily: ctx.token('font.family'),
              fontSize: 20,
              textGrowth: 'fixed-width',
              width: 'fill_container',
            },
          ),
          frame(
            'hp-ctas',
            { name: 'CTAs', layout: 'horizontal', gap: 16, alignItems: 'center' },
            [
              ref('hp-cta-primary', ctx.component('button'), {
                descendants: { 'button-label': { content: 'Get started' } },
              }),
              ref('hp-cta-secondary', ctx.component('button'), {
                fill: ctx.token('color.surface'),
                stroke: {
                  thickness: ctx.token('border.width'),
                  fill: ctx.token('color.border'),
                },
                descendants: {
                  'button-label': {
                    content: 'Documentation',
                    fill: ctx.token('color.foreground'),
                  },
                },
              }),
            ],
          ),
        ],
      );

      const featureCopy: { title: string; sub: string }[] = [
        { title: 'Tokens, not hex', sub: 'Every value flows from themeable design tokens.' },
        { title: 'Atomic by default', sub: 'Reusable components compose into screens.' },
        { title: 'Pencil-native', sub: 'Single-file .pen that opens in the app.' },
      ];
      const features = frame(
        'hp-features',
        { name: 'Features', layout: 'horizontal', width: 'fill_container', gap: 24, alignItems: 'start' },
        featureCopy.map((f, i) =>
          ref(`hp-card-${i}`, ctx.component('card'), {
            width: 'fill_container',
            descendants: {
              'card-title': { content: f.title },
              'card-subtitle': { content: f.sub },
              'card-body-text': { content: 'Learn how it fits your stack.' },
            },
          }),
        ),
      );

      const footer = text('hp-footer', 'Generated with mech-pencil — single-file .pen', {
        fill: ctx.token('color.muted'),
        fontFamily: ctx.token('font.family'),
        fontSize: 14,
      });

      return [
        frame(
          'screen',
          {
            name: 'Template',
            width: 1280,
            height: 1024,
            fill: ctx.token('color.background'),
            theme: { mode: 'light' },
            layout: 'vertical',
            gap: 48,
            padding: [80, 64, 80, 64],
          },
          [navbar, hero, features, footer],
        ),
      ];
    },
  };
}

export const heroUIAdapter: FrameworkAdapter = {
  id: 'heroui',
  title: 'HeroUI v3',
  description:
    'HeroUI v3 (@heroui/react + @heroui/styles) — OKLCH CSS-variable ' +
    'tokens, light/dark, ~72-component atomic catalog.',
  reference: 'https://heroui.com/docs/react/getting-started/llms-txt',

  tokens(): TokenSet {
    return derived().tokens;
  },

  components(): ComponentSpec[] {
    return heroUIComponents();
  },

  mockups(): MockupSpec[] {
    return [templateMockup()];
  },

  notes(): string[] {
    const out: string[] = [];
    const d = derived();
    const { total, rich } = catalogStats();
    if (d.note) out.push(d.note);
    out.push(
      `catalog: ${total} components (${rich} hand-authored, ${total - rich} token stubs)`,
    );
    return out;
  },
};
