// AUTO-GENERATED by `mech-pencil build-library`. Do not edit by hand.
//
// Static `with { type: "file" }` imports so the committed HeroUI .pen
// library is embedded into `bun build --compile` binaries (and resolves
// to real on-disk paths in dev/tests). Read via node:fs.

import f0 from './library/core/buttons.lib.pen' with { type: 'file' };
import f1 from './library/core/buttons.preview.pen' with { type: 'file' };
import f2 from './library/core/collections.lib.pen' with { type: 'file' };
import f3 from './library/core/collections.preview.pen' with { type: 'file' };
import f4 from './library/core/colors.lib.pen' with { type: 'file' };
import f5 from './library/core/colors.preview.pen' with { type: 'file' };
import f6 from './library/core/controls.lib.pen' with { type: 'file' };
import f7 from './library/core/controls.preview.pen' with { type: 'file' };
import f8 from './library/core/data-display.lib.pen' with { type: 'file' };
import f9 from './library/core/data-display.preview.pen' with { type: 'file' };
import f10 from './library/core/date-and-time.lib.pen' with { type: 'file' };
import f11 from './library/core/date-and-time.preview.pen' with { type: 'file' };
import f12 from './library/core/feedback.lib.pen' with { type: 'file' };
import f13 from './library/core/feedback.preview.pen' with { type: 'file' };
import f14 from './library/core/forms.lib.pen' with { type: 'file' };
import f15 from './library/core/forms.preview.pen' with { type: 'file' };
import f16 from './library/core/layout.lib.pen' with { type: 'file' };
import f17 from './library/core/layout.preview.pen' with { type: 'file' };
import f18 from './library/core/media.lib.pen' with { type: 'file' };
import f19 from './library/core/media.preview.pen' with { type: 'file' };
import f20 from './library/core/navigation.lib.pen' with { type: 'file' };
import f21 from './library/core/navigation.preview.pen' with { type: 'file' };
import f22 from './library/core/overlays.lib.pen' with { type: 'file' };
import f23 from './library/core/overlays.preview.pen' with { type: 'file' };
import f24 from './library/core/pickers.lib.pen' with { type: 'file' };
import f25 from './library/core/pickers.preview.pen' with { type: 'file' };
import f26 from './library/core/typography.lib.pen' with { type: 'file' };
import f27 from './library/core/typography.preview.pen' with { type: 'file' };
import f28 from './library/core/utilities.lib.pen' with { type: 'file' };
import f29 from './library/core/utilities.preview.pen' with { type: 'file' };
import f30 from './library/design-system/atoms.lib.pen' with { type: 'file' };
import f31 from './library/design-system/atoms.preview.pen' with { type: 'file' };
import f32 from './library/design-system/molecules.lib.pen' with { type: 'file' };
import f33 from './library/design-system/molecules.preview.pen' with { type: 'file' };
import f34 from './library/design-system/organisms.lib.pen' with { type: 'file' };
import f35 from './library/design-system/organisms.preview.pen' with { type: 'file' };
import f36 from './library/design-system/templates.lib.pen' with { type: 'file' };
import f37 from './library/design-system/templates.preview.pen' with { type: 'file' };
import f38 from './library/design-tokens.lib.pen' with { type: 'file' };
import f39 from './library/mocks/template.pen' with { type: 'file' };

export interface EmbeddedLibFile {
  /** Path under the library root, POSIX-separated. */
  rel: string;
  /** File path to read with node:fs (real in dev, $bunfs when compiled). */
  path: string;
}

export const EMBEDDED_LIBRARY: readonly EmbeddedLibFile[] = [
  { rel: 'core/buttons.lib.pen', path: f0 },
  { rel: 'core/buttons.preview.pen', path: f1 },
  { rel: 'core/collections.lib.pen', path: f2 },
  { rel: 'core/collections.preview.pen', path: f3 },
  { rel: 'core/colors.lib.pen', path: f4 },
  { rel: 'core/colors.preview.pen', path: f5 },
  { rel: 'core/controls.lib.pen', path: f6 },
  { rel: 'core/controls.preview.pen', path: f7 },
  { rel: 'core/data-display.lib.pen', path: f8 },
  { rel: 'core/data-display.preview.pen', path: f9 },
  { rel: 'core/date-and-time.lib.pen', path: f10 },
  { rel: 'core/date-and-time.preview.pen', path: f11 },
  { rel: 'core/feedback.lib.pen', path: f12 },
  { rel: 'core/feedback.preview.pen', path: f13 },
  { rel: 'core/forms.lib.pen', path: f14 },
  { rel: 'core/forms.preview.pen', path: f15 },
  { rel: 'core/layout.lib.pen', path: f16 },
  { rel: 'core/layout.preview.pen', path: f17 },
  { rel: 'core/media.lib.pen', path: f18 },
  { rel: 'core/media.preview.pen', path: f19 },
  { rel: 'core/navigation.lib.pen', path: f20 },
  { rel: 'core/navigation.preview.pen', path: f21 },
  { rel: 'core/overlays.lib.pen', path: f22 },
  { rel: 'core/overlays.preview.pen', path: f23 },
  { rel: 'core/pickers.lib.pen', path: f24 },
  { rel: 'core/pickers.preview.pen', path: f25 },
  { rel: 'core/typography.lib.pen', path: f26 },
  { rel: 'core/typography.preview.pen', path: f27 },
  { rel: 'core/utilities.lib.pen', path: f28 },
  { rel: 'core/utilities.preview.pen', path: f29 },
  { rel: 'design-system/atoms.lib.pen', path: f30 },
  { rel: 'design-system/atoms.preview.pen', path: f31 },
  { rel: 'design-system/molecules.lib.pen', path: f32 },
  { rel: 'design-system/molecules.preview.pen', path: f33 },
  { rel: 'design-system/organisms.lib.pen', path: f34 },
  { rel: 'design-system/organisms.preview.pen', path: f35 },
  { rel: 'design-system/templates.lib.pen', path: f36 },
  { rel: 'design-system/templates.preview.pen', path: f37 },
  { rel: 'design-tokens.lib.pen', path: f38 },
  { rel: 'mocks/template.pen', path: f39 },
];
