/**
 * @agentx/agent-worker — runs an LLM agent inside a sandboxed,
 * peekable tmux session, with workspace SKILL.md content as the
 * system prompt.
 *
 * Per the agent-worker PRD (.plans/2026-04-30-prd-agent-worker-lib.md):
 *
 *   1. The harness-server spawns this worker for each job phase
 *      (or for the synthetic coordinator/checkout-coordinator
 *      agents when those become real).
 *   2. The worker redirects HOME + TMPDIR to workspace-private dirs
 *      (sandbox isolation; can't stomp host).
 *   3. It opens a tmux session named `agent-<jobId>` so a developer
 *      can `harness attach <jobId>` to watch live.
 *   4. It loads workspace SKILL.md files and concatenates them into
 *      the agent's system prompt.
 *   5. It invokes the agent via @agentx/agent-adapter; tool calls
 *      from the agent (Bash → harness CLI → UDS → triad) flow back
 *      through the SKILL.md-documented surface.
 *   6. SIGTERM shuts down the tmux session; the worker exits.
 *
 * Phase 1 (this commit): scaffold + skill loader + sandbox helpers +
 * tmux session wrapper. The runAgentWorker entry point is wired but
 * the actual LLM invocation is stubbed — it constructs the system
 * prompt and returns a deterministic "no agent runtime wired yet"
 * response. That's enough to validate the SKILL.md → prompt path
 * end-to-end without an API key. Real LLM invocation lands in a
 * follow-up slice when we add a Claude SDK adapter binding.
 */

export {
  ensureSandboxDirs,
  type SandboxPaths,
  sandboxEnv,
  sandboxPaths,
} from './sandbox.js';
export {
  buildSystemPrompt,
  type LoadedSkill,
  type LoadSkillsOptions,
  loadWorkspaceSkills,
} from './skill-prompt.js';

export {
  startAgentTmuxSession,
  type TmuxSession,
  tmuxSendCommand,
} from './tmux.js';

import { ensureSandboxDirs, sandboxEnv } from './sandbox.js';
import { buildSystemPrompt, loadWorkspaceSkills } from './skill-prompt.js';

export interface AgentWorkerSpec {
  jobId: string;
  workspaceRoot: string;
  /** The actual user-facing task for the agent. Free-form text. */
  task: string;
  /** Restrict to specific skill names (without `.md`) when injecting
   *  the system prompt. Default: all skills found. */
  skills?: string[];
  /** Whether to actually create a tmux session. Default: false (so
   *  unit tests don't require tmux on the test host). When the
   *  harness-server invokes this worker for real, it'll set true. */
  createTmuxSession?: boolean;
  /** Override for the agent invocation function. Tests pass a stub;
   *  production wires a Claude SDK / opencode-cli adapter. Default:
   *  the no-runtime placeholder that returns a deterministic message. */
  invokeAgent?: (args: { systemPrompt: string; task: string }) => Promise<string>;
}

export interface AgentWorkerResult {
  jobId: string;
  /** The system prompt the agent saw — useful for debugging the
   *  skill-injection path independently of the LLM response. */
  systemPrompt: string;
  /** The agent's final response to the task. */
  response: string;
  /** Skills loaded into the prompt. */
  skillNames: string[];
  /** Did this run actually create a tmux session? */
  hadTmuxSession: boolean;
}

/** Default agent invocation: returns a deterministic placeholder so the
 *  worker chain is fully exercised without an LLM runtime wired. */
async function noRuntimeAgent(args: { systemPrompt: string; task: string }): Promise<string> {
  return [
    '[agent-worker placeholder]',
    'No LLM runtime wired yet — this response is generated by the worker',
    'itself rather than a real agent. The system prompt the agent would',
    `have seen is ${args.systemPrompt.length} chars long.`,
    '',
    `Task received: ${args.task}`,
    '',
    'Wire a Claude SDK / opencode-cli adapter via spec.invokeAgent to run',
    'real LLM-driven work.',
  ].join('\n');
}

/**
 * Run an agent worker end to end:
 *   1. ensure sandbox dirs
 *   2. load skills + build system prompt
 *   3. (optional) start tmux session for peeking
 *   4. invoke the agent with the system prompt + task
 *   5. tear down tmux + return result
 *
 * Returns the agent's response. Errors propagate; the harness-server
 * caller is responsible for translating those into job-status changes.
 */
export async function runAgentWorker(spec: AgentWorkerSpec): Promise<AgentWorkerResult> {
  await ensureSandboxDirs(spec.workspaceRoot);

  const skills = await loadWorkspaceSkills({
    workspaceRoot: spec.workspaceRoot,
    skills: spec.skills,
  });
  const systemPrompt = buildSystemPrompt({
    jobId: spec.jobId,
    workspaceRoot: spec.workspaceRoot,
    skills,
  });

  let tmuxSession: import('./tmux.js').TmuxSession | null = null;
  if (spec.createTmuxSession) {
    const { startAgentTmuxSession } = await import('./tmux.js');
    tmuxSession = await startAgentTmuxSession({
      workspaceRoot: spec.workspaceRoot,
      jobId: spec.jobId,
    });
  }

  try {
    const invoke = spec.invokeAgent ?? noRuntimeAgent;
    const response = await invoke({ systemPrompt, task: spec.task });
    return {
      jobId: spec.jobId,
      systemPrompt,
      response,
      skillNames: skills.map((s) => s.name),
      hadTmuxSession: tmuxSession !== null,
    };
  } finally {
    if (tmuxSession) await tmuxSession.kill();
  }
}

/** Build the env-redirect record a child process of the worker should
 *  inherit. Re-exported here for callers that don't want to import
 *  from `./sandbox.ts` directly. */
export { sandboxEnv as workerEnv };
