/**
 * The committed, theme-invariant HeroUI `.pen` library.
 *
 * The HeroUI component layer (core + previews + design-system +
 * design-tokens + mock skeletons) is byte-identical across every theme
 * — pure `$tokens:` references (verified). It's generated ONCE by
 * `mech-pencil build-library`, committed under the heroui framework,
 * and `bundle` REUSES it (only `design-tokens.lib.pen` is per-project).
 *
 * Two deliberately separated concerns so `bun build --compile` works:
 *
 *  • READ  (libraryExists / copyLibrary) — consumed by `bundle`.
 *    Backed by the generated `frameworks/heroui/library-embed.ts`
 *    (static `with { type: "file" }` imports). `bun build` embeds
 *    those bytes into a `--compile` binary; in dev they resolve to
 *    real paths. Either way `node:fs` reads them (Bun's `$bunfs/…`
 *    embedded paths are readable through `node:fs`).
 *
 *  • WRITE (libraryDir / resetLibraryDir / writeEmbedManifest) — the
 *    MAINTAINER `build-library` path. Only ever runs from source, never
 *    from a compiled binary, so it keeps walking the filesystem to the
 *    package root.
 */

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EMBEDDED_LIBRARY } from '../frameworks/heroui/library-embed.ts';

const HEROUI_LIBRARY_REL = 'src/frameworks/heroui/library';
const EMBED_MANIFEST_REL = 'src/frameworks/heroui/library-embed.ts';

/** Sentinel `build-library` always emits — stable across layout changes. */
const SENTINEL = 'design-tokens.lib.pen';

// ── READ path (embedded; works in dev, tests, and --compile) ─────────

export function libraryExists(): boolean {
  const sentinel = EMBEDDED_LIBRARY.find((f) => f.rel === SENTINEL);
  if (!sentinel) return false;
  try {
    readFileSync(sentinel.path);
    return true;
  } catch {
    return false;
  }
}

/** Write the embedded HeroUI library tree into `dest`. */
export function copyLibrary(dest: string): void {
  for (const { rel, path } of EMBEDDED_LIBRARY) {
    const out = join(dest, ...rel.split('/'));
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, readFileSync(path));
  }
}

// ── WRITE path (maintainer / source-only) ────────────────────────────

/** Walk up from this module to the @ecruz165/mech-pencil package root. */
function packageRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 6; i++, dir = dirname(dir)) {
    try {
      const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
      if (pkg.name === '@ecruz165/mech-pencil') return dir;
    } catch {
      /* keep walking */
    }
  }
  throw new Error('mech-pencil: could not locate package root');
}

/** Absolute path of the committed static HeroUI library directory. */
export function libraryDir(): string {
  return join(packageRoot(), HEROUI_LIBRARY_REL);
}

/**
 * Wipe + recreate the committed library dir so a regenerate can never
 * leave orphans behind (files removed/renamed in the catalog).
 * `build-library` calls this before writing.
 */
export function resetLibraryDir(): void {
  const dir = libraryDir();
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
}

/**
 * Regenerate `frameworks/heroui/library-embed.ts` from the on-disk
 * library so the static embed imports stay in lockstep with whatever
 * `build-library` just wrote (catalog adds / removes / renames).
 * Idempotent: re-running on an unchanged tree yields byte-identical
 * output (sorted), so it never churns the committed file.
 */
export function writeEmbedManifest(): void {
  const rels = readdirSync(libraryDir(), { recursive: true })
    .map(String)
    .filter((p) => p.endsWith('.pen'))
    .map((p) => p.split(sep).join('/'))
    .sort();

  const out: string[] = [
    '// AUTO-GENERATED by `mech-pencil build-library`. Do not edit by hand.',
    '//',
    '// Static `with { type: "file" }` imports so the committed HeroUI .pen',
    '// library is embedded into `bun build --compile` binaries (and resolves',
    '// to real on-disk paths in dev/tests). Read via node:fs.',
    '',
  ];
  rels.forEach((rel, i) => {
    out.push(`import f${i} from './library/${rel}' with { type: 'file' };`);
  });
  out.push(
    '',
    'export interface EmbeddedLibFile {',
    '  /** Path under the library root, POSIX-separated. */',
    '  rel: string;',
    '  /** File path to read with node:fs (real in dev, $bunfs when compiled). */',
    '  path: string;',
    '}',
    '',
    'export const EMBEDDED_LIBRARY: readonly EmbeddedLibFile[] = [',
  );
  rels.forEach((rel, i) => {
    out.push(`  { rel: '${rel}', path: f${i} },`);
  });
  out.push('];', '');

  writeFileSync(join(packageRoot(), EMBED_MANIFEST_REL), out.join('\n'));
}
