import path from "node:path";

export type FileType = "app" | "test" | "config" | "storybook" | "doc";

// ── Default ignore patterns ────────────────────────────────────────────────
// System-generated files that inflate metrics without representing real work.
// Users can override or extend via config.settings.ignore_patterns.

const DEFAULT_IGNORE_PATTERNS: string[] = [
  // Lock files (auto-generated by package managers)
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "composer.lock",
  "Gemfile.lock",
  "Cargo.lock",
  "poetry.lock",
  "Pipfile.lock",
  // Minified / bundled output
  "*.min.js",
  "*.min.css",
  "*.bundle.js",
  "*.chunk.js",
  // Source maps
  "*.map",
  // Build output directories
  "dist/*",
  "build/*",
  ".next/*",
  // Auto-generated files
  "*.generated.*",
  "*.auto.*",
];

/**
 * Compile a list of glob-like patterns into a matcher function.
 *
 * Supported syntax (intentionally minimal):
 * - Exact basename match: "package-lock.json"
 * - Wildcard prefix: "*.min.js"  (matches any file ending in .min.js)
 * - Directory prefix: "dist/*"   (matches any file under dist/)
 * - Wildcard infix: "*.generated.*" (matches foo.generated.ts)
 */
export function buildIgnoreMatcher(
  userPatterns?: string[],
): (filePath: string) => boolean {
  const patterns = userPatterns ?? DEFAULT_IGNORE_PATTERNS;

  // Pre-compile patterns into fast checkers
  const matchers: Array<(lower: string, baseLower: string) => boolean> = [];

  for (const pattern of patterns) {
    const p = pattern.toLowerCase();

    if (p.startsWith("**/")) {
      // Recursive glob: "**/*.test.ts" → match the suffix anywhere in the path
      const suffix = p.slice(3);
      if (suffix.startsWith("*.") && suffix.lastIndexOf("*") === 0) {
        const ext = suffix.slice(1);
        matchers.push((_lower, baseLower) => baseLower.endsWith(ext));
      } else {
        const escaped = p.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
        const re = new RegExp(`^${escaped}$`);
        matchers.push((lower) => re.test(lower));
      }
    } else if (p.includes("/")) {
      // Directory pattern like "dist/*" — match path prefix
      const prefix = p.replace(/\/\*$/, "/");
      matchers.push((lower) => lower.startsWith(prefix) || lower.includes(`/${prefix}`));
    } else if (p.startsWith("*.") && p.lastIndexOf("*") === 0) {
      // Simple suffix pattern like "*.min.js"
      const suffix = p.slice(1); // ".min.js"
      matchers.push((_lower, baseLower) => baseLower.endsWith(suffix));
    } else if (p.includes("*")) {
      // Convert glob to regex: "*.generated.*" → /^.*\.generated\..*$/
      const escaped = p.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
      const re = new RegExp(`^${escaped}$`);
      matchers.push((_lower, baseLower) => re.test(baseLower));
    } else {
      // Exact basename match: "package-lock.json"
      matchers.push((_lower, baseLower) => baseLower === p);
    }
  }

  return (filePath: string): boolean => {
    const normalized = filePath.replace(/\\/g, "/").toLowerCase();
    const baseLower = path.basename(normalized).toLowerCase();
    return matchers.some((m) => m(normalized, baseLower));
  };
}

export { DEFAULT_IGNORE_PATTERNS };

/**
 * Build a classifier function from user-defined glob→category rules.
 * Returns a function that checks user rules first, then falls back to
 * built-in classification. User rules use the same glob syntax as ignore patterns.
 *
 * Example rules: { "*.tf": "config", "*.proto": "app", "src/generated/**": "config" }
 */
export function buildClassifier(
  userRules?: Record<string, FileType>,
): (filePath: string) => FileType {
  if (!userRules || Object.keys(userRules).length === 0) {
    return classifyFile;
  }

  // Pre-compile user rules into fast matchers (same logic as buildIgnoreMatcher)
  const rules: Array<{ match: (lower: string, baseLower: string) => boolean; category: FileType }> = [];

  for (const [pattern, category] of Object.entries(userRules)) {
    const p = pattern.toLowerCase();

    if (p.startsWith("**/")) {
      // Recursive glob: "**/*.test.ts" → match the suffix anywhere in the path
      const suffix = p.slice(3);
      if (suffix.startsWith("*.") && suffix.lastIndexOf("*") === 0) {
        const ext = suffix.slice(1);
        rules.push({ match: (_lower, baseLower) => baseLower.endsWith(ext), category });
      } else {
        const escaped = p.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
        const re = new RegExp(`^${escaped}$`);
        rules.push({ match: (lower) => re.test(lower), category });
      }
    } else if (p.includes("/") && p.endsWith("/**")) {
      // Directory wildcard: "src/generated/**" matches anything under that dir
      const prefix = p.slice(0, -2); // "src/generated/"
      rules.push({
        match: (lower) => lower.startsWith(prefix) || lower.includes(`/${prefix}`),
        category,
      });
    } else if (p.includes("/")) {
      // Directory pattern: "dist/*" matches files directly under dist/
      const prefix = p.replace(/\/\*$/, "/");
      rules.push({
        match: (lower) => lower.startsWith(prefix) || lower.includes(`/${prefix}`),
        category,
      });
    } else if (p.startsWith("*.") && p.lastIndexOf("*") === 0) {
      // Simple suffix: "*.tf" matches any file ending in .tf
      const suffix = p.slice(1);
      rules.push({
        match: (_lower, baseLower) => baseLower.endsWith(suffix),
        category,
      });
    } else if (p.includes("*")) {
      // General glob: convert to regex
      const escaped = p.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
      const re = new RegExp(`^${escaped}$`);
      rules.push({
        match: (_lower, baseLower) => re.test(baseLower),
        category,
      });
    } else {
      // Exact basename match
      rules.push({
        match: (_lower, baseLower) => baseLower === p,
        category,
      });
    }
  }

  return (filePath: string): FileType => {
    const normalized = filePath.replace(/\\/g, "/").toLowerCase();
    const baseLower = path.basename(normalized).toLowerCase();

    // Check user rules first (first match wins)
    for (const rule of rules) {
      if (rule.match(normalized, baseLower)) {
        return rule.category;
      }
    }

    // Fall back to built-in classification
    return classifyFile(filePath);
  };
}

/**
 * Classify a file path into one of five categories.
 * Ordered rule matching: first match wins.
 *
 * Priority 1: storybook
 * Priority 2: test
 * Priority 3: config
 * Priority 4: doc
 * Priority 5: app (everything else)
 */
export function classifyFile(filePath: string): FileType {
  const normalized = filePath.replace(/\\/g, "/");
  const base = path.basename(normalized);
  const lower = normalized.toLowerCase();
  const baseLower = base.toLowerCase();

  // ── Priority 1: Storybook ──────────────────────────────────────────────────
  // .stories.*, .story.*, .storybook/, .mdx in storybook paths
  if (/\.stories\./.test(baseLower)) return "storybook";
  if (/\.story\./.test(baseLower)) return "storybook";
  if (lower.includes(".storybook/") || lower.includes("/.storybook/")) return "storybook";
  if (baseLower.endsWith(".mdx") && lower.includes("stor")) return "storybook";

  // ── Priority 2: Test ───────────────────────────────────────────────────────
  // .test.*, .spec.*, .cy.*, .e2e.*, __tests__/, /tests?/, vitest.config,
  // jest.config, cypress/, playwright/
  if (/\.test\.\w+$/.test(baseLower)) return "test";
  if (/\.spec\.\w+$/.test(baseLower)) return "test";
  if (/\.cy\.\w+$/.test(baseLower)) return "test";
  if (/\.e2e\.\w+$/.test(baseLower)) return "test";
  if (lower.includes("__tests__/") || lower.includes("/__tests__/")) return "test";
  if (/\/(tests?)\//i.test(lower)) return "test";
  if (/^vitest\.config/i.test(baseLower)) return "test";
  if (/^jest\.config/i.test(baseLower)) return "test";
  if (lower.includes("cypress/")) return "test";
  if (lower.includes("playwright/")) return "test";

  // ── Priority 3: Config ─────────────────────────────────────────────────────
  // .config.*, *.json, *.yml, *.yaml, *.toml, *.env*, Dockerfile,
  // docker-compose, .github/, *.lock, Makefile, .eslintrc, .prettier*,
  // tsconfig*, webpack.config, vite.config
  if (/\.config\.\w+$/.test(baseLower)) return "config";
  if (baseLower.endsWith(".json")) return "config";
  if (baseLower.endsWith(".yml")) return "config";
  if (baseLower.endsWith(".yaml")) return "config";
  if (baseLower.endsWith(".toml")) return "config";
  if (baseLower.includes(".env")) return "config";
  if (/^dockerfile/i.test(baseLower)) return "config";
  if (/^docker-compose/i.test(baseLower)) return "config";
  if (lower.includes(".github/")) return "config";
  if (baseLower.endsWith(".lock")) return "config";
  if (/^makefile$/i.test(baseLower)) return "config";
  if (/^\.eslintrc/i.test(baseLower)) return "config";
  if (/^\.prettier/i.test(baseLower)) return "config";
  if (/^tsconfig/i.test(baseLower)) return "config";
  if (/^webpack\.config/i.test(baseLower)) return "config";
  if (/^vite\.config/i.test(baseLower)) return "config";

  // ── Priority 4: Documentation ─────────────────────────────────────────────
  // .md (not .mdx in storybook paths, already handled above), .txt in /docs/,
  // README, CHANGELOG, CONTRIBUTING, LICENSE
  if (baseLower.endsWith(".md")) return "doc";
  if (lower.includes("/docs/") || lower.startsWith("docs/") || lower.includes("/documentation/") || lower.startsWith("documentation/")) return "doc";
  if (/^readme/i.test(baseLower)) return "doc";
  if (/^changelog/i.test(baseLower)) return "doc";
  if (/^contributing/i.test(baseLower)) return "doc";
  if (/^license/i.test(baseLower)) return "doc";

  // ── Priority 5: App (everything else) ──────────────────────────────────────
  return "app";
}
